### PR TITLE
Downgrading Hyper API Version

### PR DESCRIPTION
**Pull request by WillAyd**

### CODE REVIEW

**Comment by WillAyd** [comment]
I assume you are using a Mac with a M1 chip or newer. Unfortunately those releases have been broken with pantab, so we haven't been able to cut a release with those. For the time being you will have to continue using Rosetta

**Comment by tucheck24** [comment]
Thanks. Yes, i have an M2 / Siclicon chip. Using the rosetta workaround is a bit of a pain. Is fixing the compatibility with Apple Silicon still on your roadmap in general?

**Comment by WillAyd** [comment]
It is, but we unfortunately will need the issues with the Tableau Hyper API to be fixed first, which is entirely out of our control

If you are on the Tableau Slack I have an active thread going with their dev team about regressions that started with the `19484.rdb1797f2` release (i.e., the first to support Apple Silicon) in the help-hyper-api channel. You are welcome to track the discussion there, and of course chime in with any input

**Comment by tucheck24** [comment]
Great, thanks a lot for the effort and the tipp with the slack channel for the latest news!

**Pull request merged**
