### PR TITLE
sphinx_rtd_theme addition for make html issue

### LINKED ISSUE #105: sphinx_rtd_theme module needs to be included to make the html docs
**Describe the bug**
When running `make html` in the /doc folder as per the CONTRIBUTING.md instructions, this error occurs:

```
Running Sphinx v3.0.3

Extension error:
Could not import extension sphinx_rtd_theme (exception: No module named 'sphinx_rtd_theme')
```

**To Reproduce**

Run this in the /doc folder after fresh creation of pantab-dev environment:
```
make html
```

**Expected behavior**
The /build folder should be created with HTML documentation in the /doc folder.

**Desktop (please complete the following information):**
 - macOS Catalina Version 10.15.5 (19F96)

**Additional context**
Recommended to add sphinx_rtd_theme to the environment.yml file under '- pip` section as this resolved my build for HTML documentation.

### PR DESCRIPTION
**Pull request by c-l-nguyen**
closes #105

### CODE REVIEW

**Comment by WillAyd** [comment]
Can this just be in the normal section for conda? I think available in the default channel

**Comment by c-l-nguyen** [comment]
Ah yes, it can. I will correct that and push the change. Thanks for that catch!

**Comment by WillAyd** [comment]
Thanks for these cleanups - super useful for future contributors

**Comment by c-l-nguyen** [comment]
You're welcome! I'm happy to contribute any way I can and I'm having fun learning how to contribute to an open source project haha

**Pull request merged**
