### PR TITLE
ci: update cibw to 2.21.3

### LINKED ISSUE #371: 3.13 Wheels not Posted to PyPi
Thought this was fixed but double checked and we are not pushing 3.13 wheels to pypi. Any help investigating would be appreciated!

### PR DESCRIPTION
**Pull request by jorwoods**
closes #371

### CODE REVIEW

**Comment by jorwoods** [comment]
Per https://github.com/apache/arrow/issues/44443, no pyarrow wheels released for 3.13 until pyarrow version 18 has been released. This PR otherwise should fix the pantab pipeline such that it runs tests and builds for python 3.13.

**Comment by WillAyd** [comment]
Looks like pyarrow 18 was released a few days ago - worth trying again?

**Comment by jorwoods** [comment]
@WillAyd Builds are now working. Reading to review.

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Awesome thanks @jorwoods 

I'm going to create a RC for the next minor version soon. We can release wheels as part of that

**Pull request merged**
