### PR TITLE
163 frames from hyper not pulling

### PR DESCRIPTION
**Pull request by VDFaller**
This at least writes a test that currently fails for #163 , doesn't actually fix.

### CODE REVIEW

**Comment by WillAyd** [comment]
Test looks great. To your comment in the code shouldn’t need to unlink that - the test fixtures should do that on its own

Have an idea on how to fix or need guidance?

**Comment by VDFaller** [comment]
I was looking at `conftest.py` but couldn't see anyplace where it unlinked.  I can just steal from basic and see what you say.

**Comment by WillAyd** [comment]
Yea pytest is an amazing tool but conftest is a little strange at first. If you look here:

https://github.com/innobi/pantab/blob/f6a9fbb3f73cd51ada79e5d6d6aa114aea77dc98/pantab/tests/conftest.py#L138

You’ll see we are using the tmp_path fixture provided by pytest

https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html

**Comment by VDFaller** [comment]
Oh that's WAY better than what I usually do.  Live and learn.

**Comment by WillAyd** [comment]
@VDFaller did you want to work on the fix to go along with this test?

**Comment by WillAyd** [comment]
Closing as I think this is stale but would definitely take it if its something you want to pick back up @VDFaller

**Pull request closed without merging**
