### PR TITLE
Added Python 3.11 wheels building support

### LINKED ISSUE #178: Python 3.11 - pantab/src/pantab.c:6:10: fatal error: 'cffi.h' file not found
**Describe the bug**
Cannot pip install pantab

**To Reproduce**

```
pip install pantab
```

**Expected behavior**
Successfully installed pantab

**Screenshots**
      pantab/src/pantab.c:6:10: fatal error: 'cffi.h' file not found
      #include "cffi.h"
               ^~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pantab
Failed to build pantab
ERROR: Could not build wheels for pantab, which is required to install pyproject.toml-based projects

**Desktop (please complete the following information):**
 - OS: MacOS 13.2.1

**Additional context**
This is for Pantab 3.0.0
An older version of Pantab will install correctly (1.1.1)

### PR DESCRIPTION
**Pull request by Installka**
Added Python 3.11 to wheels building files mentioned in [comment](https://github.com/innobi/pantab/issues/178#issuecomment-1504227525).

closes #178

### CODE REVIEW

**Comment by WillAyd** [comment]
Awesome thanks for this! I think the test failures are all related to https://github.com/innobi/pantab/issues/186

Assuming we can fix that soon will  cut a new release and get the 3.11 wheels on pypi with that

**Comment by WillAyd** [comment]
@Installka can you also check setup.py? Should add 3.11 to the classifiers section there

**Comment by Installka** [comment]
Yeah, I performed tests on my machine and founded this problem with timestamp conversion from #186. Hopefully workaround from #187 will do it.

I'll update **setup.py** tomorrow.

**Comment by WillAyd** [comment]
Lost this in the shuffle - sorry for the delay but thanks a ton @Installka

**Pull request merged**
