### PR TITLE
Add option to not raise an error in case of invalid timestamps

### LINKED ISSUE #174: OutOfBoundsDatetime Error
I'm trying to read a .hyper file using 

```python
df = pantab.frames_from_hyper(filename)
```
but I'm getting an error

```
OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 9999-12-31 00:00:00
```

Seems like there is a corrupted timestamp in the .hyper file, but is there any way I can ignore the error so the file can be loaded?  Pandas has ```errors='coerce'``` which seems like a nice idea.  Any other workarounds would be helpful!  The file does load in Tableau, so I'm a little stuck on how to read this into a pandas dataframe.

### PR DESCRIPTION
**Pull request by pdillens**
Current implementation does not allow to coerce or ignore errors, if read data contains datetime columns with invalid timestamps (e.g. timestamps out of bounds). This commit implements an additional option to set the error handling for datetime columns.

closes   #174 

PS: Not sure if it is the main branch is the preferred branch to ask for a pull request here, just let me know if I should switch to a different branch.

Cheers Pascal

### CODE REVIEW

**Comment by WillAyd** [comment]
Hey thanks a ton for the PR! Looks like there is a syntax error tripping things up. Can you also add a few test cases so we know this works?

**Comment by pdillens** [comment]
Hi, I fixed the syntax error. About the test cases I fear it will be difficult for me to add them, since, I am not very experienced with python and do not have the time for extensive reading up on it.
From the conceptual side I think two test cases would be required:
1. Nothing changed in the case that no explicit date_errors argument is passed
   - Invalid timestamps especially "Out of bounds timestamps" (e.g. `Timestamp(2301-01-01, utc=True)`) lead to a raised error
2. date_errors argument is set to "coerce" or "ignore"
   - The result matches the expected behavior from [pandas to_datetime](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html?highlight=to_datetime#pandas.to_datetime):
   - coerce leads to NaT
   - ignore leads to the input being returned and a object dtype

**Comment by WillAyd** [comment]
You can look at the tests in https://github.com/innobi/pantab/blob/main/pantab/tests/test_reader.py to get a feel for what needs to be done. Since you've run into the issue before I would create a hyper file that can minimally reproduce it, then try to read it in with the keywords and observe the expected values

**Comment by WillAyd** [comment]
This would be a good thing to have but needs tests so we know it works and continues to work. Closing for now but if you are anyone else is interested in continuing ping back here and can reopen. Thanks!

**Pull request closed without merging**
